export interface SeedMenuDrink {
  name: string;
  description: string;
  price: number;
  credit_price: number;
  category: 'espresso' | 'cold_brew' | 'latte' | 'specialty';
  is_signature: boolean;
  image_url: string;
}

export const CAFE_MENUS: Record<string, SeedMenuDrink[]> = {
  'Bloom & Brew': [
    {
      name: 'Espresso',
      description: 'Rich single-origin shot with notes of red currant and chocolate.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double extraction with velvety golden crema.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Ristretto',
      description: 'Short, concentrated shot highlighting sweet floral aromatics.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Hot water pulled through a double espresso shot.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: 'Equal parts espresso and lightly textured warm milk.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Espresso crowned with thick, dense foam and cocoa dust.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Double ristretto poured over velvety microfoam.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Silky steamed whole milk with a rich double espresso base.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Espresso, organic dark Dutch chocolate, and steamed milk.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Rose Latte',
      description: 'Artisanal Damask rose water, espresso, and steamed milk.',
      price: 5.75,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Lavender Latte',
      description: 'House-infused lavender syrup, espresso, and creamy oat milk.',
      price: 6.0,
      credit_price: 5,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Vanilla Bean Latte',
      description: 'Madagascar bourbon vanilla syrup with espresso and microfoam.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: 'Steeped for 18 hours in cold filtered mountain water.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew Latte',
      description: 'Slow-steeped cold brew layered over sweet condensed milk.',
      price: 5.5,
      credit_price: 4,
      category: 'cold_brew',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Chilled espresso over crystal ice and filtered water.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Espresso and fresh cold milk poured over ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Mocha',
      description: 'Chilled dark chocolate ganache, double espresso, and milk.',
      price: 5.75,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Honey Cinnamon Latte',
      description: 'Wild mountain honey and Ceylon cinnamon with espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Creamy steamed barista oat milk over espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Vietnamese Iced Coffee',
      description: 'Robusta drip coffee over sweet condensed milk on ice.',
      price: 5.25,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'NOFC': [
    {
      name: 'Single Espresso',
      description: 'Bright, citrus-forward roast with clean finish.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Bold double shot crafted on a La Marzocco.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Long Black',
      description: 'Double espresso floated over hot mineral water.',
      price: 3.9,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Piccolo Latte',
      description: 'Ristretto shot in a 4oz glass with silky steamed milk.',
      price: 4.0,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Australian style micro-textured whole milk over espresso.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Classic morning cappuccino with deep chocolatey notes.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Smooth double shot folded with silky steamed milk.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: 'Single-origin beans steeped cold for 20 hours.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Nitro Cold Brew',
      description: 'Nitrogen-infused cold brew with a creamy Guinness-like head.',
      price: 6.25,
      credit_price: 5,
      category: 'cold_brew',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Tonic',
      description: 'Crisp craft tonic water topped with a double espresso shot.',
      price: 5.75,
      credit_price: 4,
      category: 'cold_brew',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Coconut Latte',
      description: 'Fresh coastal coconut milk blended with dark roast espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Refreshing chilled espresso over cubed ice.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Smooth espresso and chilled whole milk over clear ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Freddo Espresso',
      description: 'Greek style shaken espresso with a frothy crema over ice.',
      price: 4.75,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Almond Milk Latte',
      description: 'House almond milk with a velvety espresso pour.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Spanish Latte',
      description: 'Sweetened condensed milk balanced with bold espresso.',
      price: 5.75,
      credit_price: 5,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Mocha',
      description: 'Cold Dutch cocoa, chilled espresso, and milk.',
      price: 5.75,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café au Lait',
      description: 'Equal parts French roast brewed coffee and steamed milk.',
      price: 4.5,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'Café Lento': [
    {
      name: 'Espresso',
      description: 'Traditional Southern European espresso extraction.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Ristretto',
      description: 'Dense sweet extraction of dark roasted Arabica.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Deep and mellow hot coffee pulled to perfection.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: 'Spanish cortado with equal parts espresso and warm milk.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Bombón',
      description: 'Layers of sweet condensed milk and intense Spanish espresso.',
      price: 5.25,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Vietnamese Coffee',
      description: 'Slow-dripped Phin filter brew over sweetened milk.',
      price: 5.25,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Fluffy frothed milk over a dark chocolatey espresso.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Classic hot latte with silky microfoam.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Bittersweet chocolate melted into hot espresso and milk.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café de Olla',
      description: 'Spiced coffee brewed with piloncillo and Mexican cinnamon.',
      price: 5.25,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: 'Slow cold extraction highlighting dark stone fruit.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Refreshing chilled espresso and milk over crystal ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Cool, crisp espresso over filtered iced water.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Macchiato',
      description: 'Double espresso with a dollop of velvety foam.',
      price: 4.0,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cinnamon Latte',
      description: 'Steamed milk infused with aromatic ground cinnamon.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Hazelnut Latte',
      description: 'Roasted hazelnut syrup with espresso and steamed milk.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Silky barista-grade oat milk and espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Affogato',
      description: 'Vanilla bean gelato drowned in a hot double espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Breve',
      description: 'Rich American latte made with steamed half-and-half.',
      price: 5.0,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'Prana Eva Café': [
    {
      name: 'Single Origin Espresso',
      description: 'Washed Ethiopian heirloom roast with jasmine and citrus notes.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double organic shot pulled at high pressure.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Long Black',
      description: 'Crisp double espresso over hot spring water.',
      price: 3.9,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Gibraltar',
      description: 'Short pour served warm in a faceted 4.5oz glass.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Silky microfoam over double espresso.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Light airy foam dusted with organic cinnamon.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Steamed organic milk combined with smooth espresso.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Almond Latte',
      description: 'Fresh house-pressed organic almond milk with light roast espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Golden Dirty Chai Latte',
      description: 'Turmeric, ginger, organic spiced chai, espresso, and oat milk.',
      price: 6.0,
      credit_price: 5,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Coconut Milk Latte',
      description: 'Creamy cold-pressed coconut milk with rich espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: 'Single-estate Arabica steeped for 24 hours.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Chilled organic milk and espresso over rocks.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Double espresso over mountain ice.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Nitro Cold Brew',
      description: 'Ultra-creamy nitro poured cold on draft.',
      price: 6.25,
      credit_price: 5,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Honey Lavender Latte',
      description: 'Organic raw honey and wild lavender flowers infused in microfoam.',
      price: 5.75,
      credit_price: 5,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cardamom Latte',
      description: 'Crushed green cardamom pods steamed with milk and espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Soy Milk Latte',
      description: 'Non-GMO organic soy milk frothed with espresso.',
      price: 5.25,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Barista oat milk steamed silky over double espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Espresso',
      description: 'Quick-chilled double espresso shaken over ice.',
      price: 4.0,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Mocha',
      description: 'Raw cacao melted into espresso and chilled almond milk.',
      price: 5.75,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Freddo Espresso',
      description: 'Blended Greek-style espresso over ice.',
      price: 4.75,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'Pisco – By the Beach': [
    {
      name: 'Espresso',
      description: 'Classic Italian dark roast espresso.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Intense double shot with lasting crema.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Smooth and aromatic black coffee.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Velvety foam and bold espresso.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Steamed milk and rich espresso.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Nitro Cold Brew',
      description: 'Cascading nitro cold brew served ice-cold from tap.',
      price: 6.25,
      credit_price: 5,
      category: 'cold_brew',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Freddo Cappuccino',
      description: 'Iced espresso crowned with cold frothed skim milk foam.',
      price: 5.25,
      credit_price: 3,
      category: 'latte',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Flat White',
      description: 'Double ristretto poured over cold milk and ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: 'Slow-steeped smooth coffee with notes of cocoa.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Double shot poured over pure ice water.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Espresso layered over cold fresh milk and ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Tonic',
      description: 'Fever Tree tonic water and a shot of espresso on ice.',
      price: 5.75,
      credit_price: 4,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Caramel Latte',
      description: 'House caramel drizzle, espresso, and warm milk.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Vanilla Latte',
      description: 'Natural vanilla extract, espresso, and steamed milk.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Cocoa syrup with espresso and steamed milk.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Coconut Latte',
      description: 'Coastal coconut milk with double shot espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Smooth oat milk latte with fine latte art.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'Purple Martini': [
    {
      name: 'Espresso',
      description: 'Clean, rich espresso with a dense crema.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double extraction for a deep coffee kick.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Lungo',
      description: 'Extended extraction highlighting bittersweet roasty notes.',
      price: 3.5,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Espresso and piping hot water.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: 'Silky textured milk cutting through intense espresso.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Espresso with thick textured milk foam.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Espresso with steamed milk and latte art.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Affogato',
      description: 'Artisanal vanilla bean gelato topped with fresh hot espresso.',
      price: 5.75,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Irish Coffee',
      description: 'Hot brewed coffee with Irish flavor notes and thick heavy cream.',
      price: 6.5,
      credit_price: 5,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Spanish Latte',
      description: 'Creamy sweetened condensed milk base under double espresso.',
      price: 6.0,
      credit_price: 5,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Salted Caramel Latte',
      description: 'Fleur de sel caramel with espresso and milk.',
      price: 6.0,
      credit_price: 5,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Mocha',
      description: 'Decadent dark chocolate mocha poured over ice.',
      price: 5.75,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: 'Signature 18-hour cold brew.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Fresh chilled milk and double espresso on ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Tonic',
      description: 'Mediterranean tonic and espresso with a twist of orange.',
      price: 5.75,
      credit_price: 4,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Rich ristretto shot with micro-steamed milk.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Almond Milk Latte',
      description: 'Nutty almond milk steamed over espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Con Panna',
      description: 'Double espresso topped with freshly whipped Chantilly cream.',
      price: 4.5,
      credit_price: 3,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'G-Shot Coffee Roastery & Cafe': [
    {
      name: 'Single Origin Ristretto',
      description: 'Concentrated 15g single origin extraction.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: "House blend roaster's profile: caramel, bergamot, hazelnut.",
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Doppio',
      description: 'Standard double shot extracted at 9 bars.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Double espresso poured over hot filtered spring water.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Long Black',
      description: 'Espresso carefully floated on hot water to preserve crema.',
      price: 3.9,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Macchiato',
      description: 'Espresso stained with two spoons of micro-foam.',
      price: 4.0,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: '1:1 ratio of espresso to warm milk.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Gibraltar',
      description: 'The specialty barista standard served in a warm Gibraltar glass.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Piccolo Latte',
      description: 'Ristretto shot in a 100ml glass with silky microfoam.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Double ristretto with micro-textured velvety whole milk.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Balanced 1/3 espresso, 1/3 steamed milk, 1/3 dense foam.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Smooth double espresso blended with micro-steamed milk.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Single-origin dark chocolate blended with house espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: '24-hour immersion cold brew from micro-lot beans.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Nitro Cold Brew',
      description: 'Nitrogen pressurized single-origin cold brew.',
      price: 6.25,
      credit_price: 5,
      category: 'cold_brew',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Dirty Chai Latte',
      description: 'Spiced black tea chai pulled with a double espresso shot.',
      price: 6.25,
      credit_price: 5,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew Latte',
      description: 'Slow cold brew topped with creamy oat milk.',
      price: 5.5,
      credit_price: 4,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Flat White',
      description: 'Chilled double ristretto with iced textured milk.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Tonic',
      description: 'Botanical Indian tonic water with light roast espresso.',
      price: 5.75,
      credit_price: 4,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Spanish Latte',
      description: 'Velvety textured milk, condensed milk, and house roast espresso.',
      price: 6.0,
      credit_price: 5,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Pistachio Latte',
      description: 'Crushed roasted Sicilian pistachios blended with espresso.',
      price: 6.25,
      credit_price: 5,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Oat milk steamed to 60°C over double espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Almond Milk Latte',
      description: 'Roasted almond milk steamed over single-origin espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Freddo Espresso',
      description: 'Shaken Greek iced espresso with dense cold foam.',
      price: 4.75,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'Baba Au Rhum': [
    {
      name: 'Espresso',
      description: 'Classic French roast espresso shot.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double dark roast extraction.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Lungo',
      description: 'Long pulled espresso with rich depth.',
      price: 3.5,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Fresh espresso lengthened with hot mineral water.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café au Lait',
      description: 'Traditional French bistro bowl of dark roast and hot milk.',
      price: 4.5,
      credit_price: 3,
      category: 'latte',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Silky micro-foam over double espresso.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Foamy Italian style cappuccino with cocoa dust.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Steamed fresh milk with house espresso.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Valrhona French chocolate melted into espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Affogato',
      description: 'Artisanal French vanilla ice cream drowned in hot espresso.',
      price: 5.75,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Con Panna',
      description: 'Double espresso topped with fresh whipped dairy cream.',
      price: 4.5,
      credit_price: 3,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Breve',
      description: 'Decadent latte prepared with steamed light cream.',
      price: 5.0,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: '18-hour cold brew steeped on site.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Chilled espresso and milk over ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Mocha',
      description: 'Chilled Valrhona chocolate, espresso, and milk.',
      price: 5.75,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Vanilla Latte',
      description: 'Bourbon vanilla bean syrup with espresso and milk.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Hazelnut Latte',
      description: 'Toasted hazelnut syrup and espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Caramel Latte',
      description: 'Rich salted caramel swirl in hot latte.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Plant-based barista oat milk with espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Almond Milk Latte',
      description: 'Almond milk microfoam with espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Crisp iced espresso and cold water.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Vietnamese Iced Coffee',
      description: 'Intense drip brew poured over ice and condensed milk.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'Artjuna Cafe': [
    {
      name: 'Espresso',
      description: 'Rich dark espresso with dense golden crema.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double extraction of Mediterranean blend.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Classic black coffee pulled with fresh espresso.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: 'Equal parts espresso and warm milk.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Frothy cappuccino with hints of cinnamon.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Microfoam layered over double ristretto.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Steamed milk and smooth espresso.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Turkish Coffee',
      description: 'Unfiltered finely ground coffee simmered in a copper cezve with cardamom.',
      price: 4.5,
      credit_price: 3,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cardamom Latte',
      description: 'Crushed green cardamom infused with espresso and steamed milk.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Mocha',
      description: 'Dark chocolate ganache with iced espresso and milk.',
      price: 5.75,
      credit_price: 4,
      category: 'latte',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: 'Slow steeped coffee served over crystal rocks.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Chilled espresso and milk over ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Refreshing chilled black coffee.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Honey Cinnamon Latte',
      description: 'Local honey and fresh cinnamon in a warm latte.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Rose Latte',
      description: 'Natural rose blossom water with espresso and milk.',
      price: 5.75,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Almond Milk Latte',
      description: 'Steamed almond milk with espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Creamy oat milk latte.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Greek Coffee',
      description: 'Traditional Greek briki brewed coffee with thick kaimaki foam.',
      price: 4.5,
      credit_price: 3,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Freddo Espresso',
      description: 'Whipped iced espresso served Mediterranean style.',
      price: 4.75,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Affogato',
      description: 'Double espresso over artisanal gelato.',
      price: 5.75,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'NU Chique': [
    {
      name: 'Espresso',
      description: 'Crisp, balanced single espresso shot.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double shot pulled from medium roast beans.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Smooth hot espresso coffee.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: 'Equal parts espresso and steamed milk.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Classic velvety cappuccino.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Steamed milk and double shot espresso.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Pistachio Latte',
      description: 'Gourmet pistachio paste, espresso, and steamed milk.',
      price: 6.25,
      credit_price: 5,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Freddo Espresso',
      description: 'Iced espresso aerated with ice for a creamy texture.',
      price: 4.75,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Vanilla Bean Latte',
      description: 'Pure Madagascar vanilla with espresso and milk.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Ristretto with textured microfoam.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: 'Slow extracted chilled coffee.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Chilled espresso and milk over ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Espresso over cold ice water.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Coconut Milk Latte',
      description: 'Fresh coconut milk with light roast espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Smooth barista oat milk latte.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Fine dark chocolate blended into hot latte.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'Shanti Cafe': [
    {
      name: 'Espresso',
      description: 'Single espresso shot with rich body.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double extraction of plantation Arabica.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Black coffee with clean chocolate finish.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'South Indian Filter Coffee',
      description: 'Traditional brass dabara filter coffee brewed with chicory and boiled milk.',
      price: 3.75,
      credit_price: 2,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cinnamon Honey Latte',
      description: 'Organic forest honey, ground cinnamon, and creamy latte.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Golden Cardamom Latte',
      description: 'Crushed green cardamom and turmeric with espresso.',
      price: 5.75,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Foamy warm cappuccino.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Steamed milk and espresso.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Microfoam over espresso.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: 'Espresso cut with warm milk.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: 'Slow brewed cold coffee.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Espresso poured over chilled milk.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Cold espresso over ice.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Coconut Milk Latte',
      description: 'Coconut milk with dark roast espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Barista oat milk latte.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Soy Milk Latte',
      description: 'Steamed soy milk with espresso.',
      price: 5.25,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Dark chocolate mocha.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Dirty Chai Latte',
      description: 'Spiced masala chai with a shot of espresso.',
      price: 6.0,
      credit_price: 5,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'Fika Coffee Co.': [
    {
      name: 'Nordic Roast Espresso',
      description: 'Light roast single origin with notes of peach and elderflower.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double shot with bright fruit acidity and sweet floral aroma.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Ristretto',
      description: 'Short pull concentrated espresso.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Long Black',
      description: 'Nordic style long black preserving maximum aromatics and crema.',
      price: 3.9,
      credit_price: 2,
      category: 'espresso',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: 'Equal parts light roast espresso and steamed milk.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cardamom Latte',
      description: 'Traditional Swedish Fika kardemumma syrup, espresso, and microfoam.',
      price: 5.75,
      credit_price: 5,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: '20-hour steeped Scandinavian roast cold brew.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Double espresso with hot water.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Classic cappuccino with silky microfoam.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Double ristretto with micro-textured milk.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Smooth double espresso with steamed whole milk.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Artisanal dark chocolate mocha.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Nitro Cold Brew',
      description: 'Smooth nitro cold brew on tap.',
      price: 6.25,
      credit_price: 5,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Flat White',
      description: 'Cold microfoam over chilled double ristretto.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Espresso and cold milk over ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Refreshing chilled black coffee.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Tonic',
      description: 'Nordic tonic water with light roast espresso shot.',
      price: 5.75,
      credit_price: 4,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Oatly barista edition steamed with light roast espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Almond Milk Latte',
      description: 'Toasted almond milk with espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Vanilla Latte',
      description: 'Vanilla bean syrup with espresso and milk.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cinnamon Latte',
      description: 'Swedish cinnamon bun inspired latte.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Affogato',
      description: 'Single origin espresso poured over vanilla gelato.',
      price: 5.75,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Macchiato',
      description: 'Espresso marked with velvety milk foam.',
      price: 4.0,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'Mojigao': [
    {
      name: 'Espresso',
      description: 'Earthy organic espresso with notes of roasted walnut.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double organic shot with rich dark body.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Clean black coffee from shade-grown beans.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: 'Balanced espresso cut with warm milk.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café de Olla',
      description: 'Clay pot brewed coffee with cinnamon, clove, and cane jaggery.',
      price: 5.25,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Steamed organic barista oat milk with jungle-grown espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Roasted Hazelnut Latte',
      description: 'House-made roasted hazelnut praline syrup with espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Frothy cappuccino dusted with raw cacao.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Micro-steamed milk over double ristretto.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Steamed milk and rich espresso.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: '24-hour slow steep cold brew.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Espresso and chilled milk over ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Chilled black coffee over ice.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Coconut Milk Latte',
      description: 'Fresh coconut milk steamed with espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Almond Milk Latte',
      description: 'Almond milk latte.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Honey Cinnamon Latte',
      description: 'Wild forest honey and cinnamon with espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Raw chocolate mocha.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Dirty Chai Latte',
      description: 'Spiced organic chai with an espresso shot.',
      price: 6.0,
      credit_price: 5,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Freddo Espresso',
      description: 'Shaken iced espresso.',
      price: 4.75,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'The Project Cafe': [
    {
      name: 'Espresso',
      description: 'Artisan espresso shot with complex chocolate notes.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double extraction.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Ristretto',
      description: 'Sweet, intense short pull.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Double espresso with hot water.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: 'Equal parts espresso and steamed milk.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Marocchino',
      description: 'Layered espresso, thick cocoa powder, and frothy milk in a glass cup.',
      price: 5.25,
      credit_price: 4,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Salted Caramel Latte',
      description: 'Artisanal salted caramel reduction, espresso, and velvety milk.',
      price: 6.0,
      credit_price: 5,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Spanish Latte',
      description: 'Rich condensed milk layered with dark espresso.',
      price: 6.0,
      credit_price: 5,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Breve',
      description: 'Steamed half-and-half cream poured over double espresso.',
      price: 5.0,
      credit_price: 3,
      category: 'latte',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Dense foam over espresso.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Smooth microfoam and double ristretto.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Classic steamed milk latte.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Italian dark chocolate mocha.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: '18-hour cold brew coffee.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew Latte',
      description: 'Cold brew with sweet cream.',
      price: 5.5,
      credit_price: 4,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Chilled espresso and milk over ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Cold espresso over ice.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Affogato',
      description: 'Vanilla gelato with hot espresso.',
      price: 5.75,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Pistachio Latte',
      description: 'Pistachio praline latte.',
      price: 6.25,
      credit_price: 5,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Barista oat milk latte.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Almond Milk Latte',
      description: 'Almond milk latte.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Con Panna',
      description: 'Espresso topped with whipped cream.',
      price: 4.5,
      credit_price: 3,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
  ],

  'Slow Tide': [
    {
      name: 'Espresso',
      description: 'Bold sunset espresso shot.',
      price: 3.25,
      credit_price: 1,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Double Espresso',
      description: 'Double shot extracted for maximum aroma.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Americano',
      description: 'Smooth black coffee with hot water.',
      price: 3.75,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cortado',
      description: 'Equal parts espresso and warm milk.',
      price: 4.25,
      credit_price: 2,
      category: 'espresso',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Espresso Tonic',
      description: 'Crisp tonic, fresh espresso, and lime over ice.',
      price: 5.75,
      credit_price: 4,
      category: 'cold_brew',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'South Indian Filter Coffee',
      description: 'Authentic frothy chicory-blended filter coffee.',
      price: 3.75,
      credit_price: 2,
      category: 'specialty',
      is_signature: true,
      image_url: 'https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cappuccino',
      description: 'Rich espresso with thick milk foam.',
      price: 4.75,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Flat White',
      description: 'Double ristretto with micro-steamed milk.',
      price: 4.85,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Café Latte',
      description: 'Steamed milk with rich espresso.',
      price: 4.95,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Mocha',
      description: 'Dark chocolate melted into espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Cold Brew',
      description: '18-hour cold brew over ice.',
      price: 4.95,
      credit_price: 3,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Nitro Cold Brew',
      description: 'Nitrogen cold brew draft.',
      price: 6.25,
      credit_price: 5,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Latte',
      description: 'Chilled espresso and milk over ice.',
      price: 5.25,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Iced Americano',
      description: 'Espresso over chilled water.',
      price: 4.25,
      credit_price: 2,
      category: 'cold_brew',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Coconut Latte',
      description: 'Coastal coconut milk with double shot espresso.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Vanilla Latte',
      description: 'Natural vanilla syrup with espresso and milk.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Caramel Latte',
      description: 'Caramel syrup with espresso and steamed milk.',
      price: 5.5,
      credit_price: 4,
      category: 'specialty',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1534778101976-62847782c213?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Oat Milk Latte',
      description: 'Barista oat milk latte.',
      price: 5.5,
      credit_price: 4,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=600',
    },
    {
      name: 'Freddo Cappuccino',
      description: 'Chilled espresso with cold foamed milk.',
      price: 5.25,
      credit_price: 3,
      category: 'latte',
      is_signature: false,
      image_url: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&q=80&w=600',
    },
  ],
};
